# Generated by Django 5.2 on 2025-04-18 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lesson_duration_alter_lesson_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
